const guests = [
    { name: "Shahzad", table: 3 },
    { name: "Saima", table: 3 },
    { name: "Areeb", table: 3 },
    { name: "Aleena", table: 3 },
    { name: "Mamoon Arshad", table: 3 },
    { name: "Naveeda Baji", table: 3 },
    { name: "Ajaz", table: 3 },
    { name: "Rumana", table: 3 },
    { name: "Saad", table: 3 },
    { name: "Hamaad", table: 3 },
    { name: "Anjum", table: 9 },
    { name: "Iftikhar", table: 9 },
    { name: "Yumna", table: 9 },
    { name: "Tayyab", table: 9 },
    { name: "Madeeha", table: 9 },
    { name: "Samdi", table: 9 },
    { name: "Bilquis", table: 9 },
    { name: "Ansari", table: 9 },
    { name: "Raheela", table: 9 },
    { name: "Afaq", table: 9 },
    { name: "Shakeel", table: 2 },
    { name: "Samra", table: 2 },
    { name: "Adil", table: 2 },
    { name: "Nabeel", table: 2 },
    { name: "Bilal", table: 2 },
    { name: "Amara", table: 2 },
    { name: "Nashwa", table: 2 },
    { name: "Ashleena", table: 2 },
    { name: "Shahzad Chaudhri", table: 2 },
    { name: "Asma", table: 2 },
    { name: "Sabrina", table: 2 },
    { name: "Sarwat", table: 4 },
    { name: "Ikram", table: 4 },
    { name: "Iffy", table: 4 },
    { name: "Iftikhar", table: 4 },
    { name: "Shakeela", table: 4 },
    { name: "Kayani", table: 4 },
    { name: "Shamaim", table: 4 },
    { name: "Juwariya ***", table: 4 },
    { name: "Aneela", table: 4 },
    { name: "Saeed", table: 4 },
    { name: "Amjad", table: 8 },
    { name: "Saima Amjad", table: 8 },
    { name: "Ammar", table: 8 },
    { name: "Mahnoor", table: 8 },
    { name: "Ayesha Kharal", table: 8 },
    { name: "Mushtaq", table: 8 },
    { name: "Mishaal", table: 8 },
    { name: "Daneen", table: 8 },
    { name: "Abdullah Kharal", table: 8 },
    { name: "Huzaifa", table: 8 },
    { name: "Zain", table: 5 },
    { name: "Afia", table: 5 },
    { name: "Naufil", table: 5 },
    { name: "Izhaan", table: 5 },
    { name: "Mariam", table: 5 },
    { name: "Raheem", table: 5 },
    { name: "Umer", table: 5 },
    { name: "Mahwish", table: 5 },
    { name: "Noor", table: 5 },
    { name: "Zina", table: 5 },
    { name: "Naveed", table: 7 },
    { name: "Sajda", table: 7 },
    { name: "Abdullah Naveed", table: 7 },
    { name: "Khdja", table: 7 },
    { name: "Shahzad Cheema", table: 7 },
    { name: "Shazia", table: 7 },
    { name: "Alia", table: 7 },
    { name: "Zeeshan", table: 7 },
    { name: "Ayesha Adeel", table: 7 },
    { name: "Adeel", table: 7 },
    { name: "Yahya", table: 6 },
    { name: "Fabiha", table: 6 },
    { name: "Omer", table: 6 },
    { name: "Ayesha", table: 6 },
    { name: "Arshia", table: 6 },
    { name: "Zafira", table: 6 },
    { name: "Verda", table: 6 },
    { name: "Sarah ***", table: 6 },
    { name: "Sarah 2", table: 6 },
    { name: "Cindy", table: 6 },
    { name: "Ahsan", table: 1 },
    { name: "Zeerak", table: 1 },
    { name: "Jaun", table: 1 },
    { name: "Aayush", table: 1 },
    { name: "Thanu", table: 1 },
    { name: "Queenie", table: 1 },
    { name: "Mathew", table: 1 },
    { name: "Julia", table: 1 },
    { name: "Chris", table: 1 },
    { name: "Ameen", table: 1 },
    { name: "Arfaa", table: 10 },
    { name: "Ahmed", table: 10 },
    { name: "Esha", table: 10 },
    { name: "Emaad", table: 10 },
    { name: "Maeesha", table: 10 },
    { name: "Hamdi", table: 10 },
    { name: "Amna", table: 10 },
    { name: "Iqra", table: 10 },
    { name: "Hafsa", table: 10 },
    { name: "Maheen", table: 10 }
];